services:
  reverse-proxy:
    image: traefik:v2.5
    command:
      - "--providers.docker"
      - "--providers.file.directory=/configuration/"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./
    labels:
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
    restart: unless-stopped
volumes:
  database: {}
